### ISSUE TITLE
Failed to activate the coverage-gutter package

### ISSUE THREAD

**Issue by agosto-levitomes** [gskachkov/tstatompackage#8]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [coverage-gutter](https://github.com/gskachkov/tstatompackage) package, v0.19.0
### Stack Trace

Failed to activate the coverage-gutter package

```
At EISDIR: illegal operation on a directory, read

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.fs.readFileSync (fs.js:438:24)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at CoverageView.module.exports.CoverageView.getCoverage (/Users/levi/.atom/packages/coverage-gutter/lib/coverage-view.coffee:56:18)
    at CoverageView.module.exports.CoverageView.showCoverage (/Users/levi/.atom/packages/coverage-gutter/lib/coverage-view.coffee:51:22)
    at CoverageView.module.exports.CoverageView.initialize (/Users/levi/.atom/packages/coverage-gutter/lib/coverage-view.coffee:45:6)
    at CoverageView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new CoverageView (/Users/levi/.atom/packages/coverage-gutter/lib/coverage-view.coffee:9:3)
    at /Users/levi/.atom/packages/coverage-gutter/lib/main.coffee:13:12
    at Array.forEach (native)
    at Object.module.exports.activate (/Users/levi/.atom/packages/coverage-gutter/lib/main.coffee:12:38)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:801:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -0:00.7.0 testcoverage:show (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/levi/projects"
  },
  "coverage-gutter": {
    "basePath": "/Users/levi/projects/agosto/contentmanager",
    "pathToLCOV": "/Users/levi/projects/agosto/contentmanager/coverage/ui/PhantomJS 1.9.8 (Mac OS X 0.0.0)"
  }
}
```
### Installed Packages

``` coffee
# User
coverage-gutter, v0.19.0
git-log, v0.4.1
linter, v1.11.3
linter-jscs, v3.4.1

# Dev
No dev packages
```

**Comment by gskachkov** [comment]
@agosto-levitomes Thanks for reporting. I'll try to find time to take a look to this issue at the weekend. Now mostly contribute to WebKit. Sorry.
